apiVersion: v1
kind: Service
metadata:
  name: test-kube-balancer-service
  namespace: test-kube-namespace
spec:
  type: LoadBalancer
  selector:
    app: test-kube
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8090