apiVersion: v1
kind: Service
metadata:
  name: test-kube-nodeport-service
  namespace: test-kube-namespace
spec:
  type: NodePort
  selector:
    app: test-kube-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8090
